import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "@/lib/query";
import Products from "@/components/Products";
import { GridBox } from "@/styles/Gridbox";
import Herosection from "@/components/Herosection";


export default function Home() {
  const [results] = useQuery({ query: PRODUCT_QUERY });


  const { fetching, data, error } = results;

  if (fetching) return <p>loading..</p>;
  if (error) return <p>ops {error.message}</p>;
  
  const products = data.products.data;


  return (
    <>
      <Head>
        <title>Bookly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Herosection/>
      <main>
        <GridBox>
          {products.map((product) => (
            <Products key={product.attributes.slug} product={product} />
          ))}
        </GridBox>
      </main>
    </>
  );
}
